export const GET_ALL_PRODUCTS_REQUEST = "products/GET_ALL_PRODUCTS_REQUEST";
export const GET_ALL_PRODUCTS_SUCCESS = "products/GET_ALL_PRODUCTS_SUCCESS";
export const GET_ALL_PRODUCTS_FAILURE = "products/GET_ALL_PRODUCTS_FAILURE";
